### ISSUE TITLE
pan.baidu.com isn't accessible in U.S.

### ISSUE THREAD

**Issue by EEngineerA** [Event-AHU/VTF_PAR#3]
Would you mind uploading the dataset and trained weights to the Google Drive platform? Unfortunately, Baidu isn't accessible in the U.S.

**Comment by wangxiao5791509** [comment]
@EEngineerA Hi, the dataset is not provided by us. It is too large (20GB) for us to update it to the Google Drive. We only have 15GB space to use for a regular account.

**Comment by wangxiao5791509** [comment]
@EEngineerA   Hi, we updated the data and pre-trained model to the DropBox, maybe you can download it now. 

https://www.dropbox.com/scl/fo/h70nbcuj4gsmi4txhq1i0/h?rlkey=rwn1gbqbjpak6d7zhp46o3rnb&dl=0

**Comment by EEngineerA** [comment]
I appreciate the dataset you provided. The code requires a pickle file, but it seems to be missing from the dataset you shared on Dropbox.

**Comment by wangxiao5791509** [comment]
@NOP1224
