### ISSUE TITLE
提供requirements.txt

### ISSUE THREAD

**Issue by Sally-lxy** [Event-AHU/VTF_PAR#4]
你好，请问可以提供requirements.txt文件吗？

**Comment by Sally-lxy** [comment]
再请问，base_block.py中的from CLIP.CoOp import *，这样调用是啥意思呢？

**Comment by NOP1224** [comment]
requirements.txt后续会更新好，from CLIP.CoOp import *这个调用与这个工作目前是无关的

**Comment by Sally-lxy** [comment]
@1125178969 好的，谢谢~
